\name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # nightly at 00:00 UTC
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: danushkumar-v
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#A8FF60&color_dots=#161b22,#2ea04333,#2ea043aa,#A8FF60,#7DF9FF

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
